version: '3'
services:
    aind:
      image: 'fuseteam/aindwm'
      privileged: true
      tty: true
      environment:
        - WEBMODE=1
      ports:
        - '5900:5900'
        - '8080:8080'
      volumes:
        - '/lib/modules:/lib/modules:ro'
        - './passwd:/home/user/.vnc'
        - './apk-pre.d:/apk-pre.d'
